const GOOGLE_SIGNUP_START = "GOOGLE_SIGNUP_START";
const GOOGLE_SIGNUP_SUCCESS = "GOOGLE_SIGNUP_SUCCESS";
const GOOGLE_SIGNUP_FAIL = "GOOGLE_SIGNUP_FAIL";

const FB_SIGNUP_START = "FB_SIGNUP_START";
const FB_SIGNUP_SUCCESS = "FB_SIGNUP_SUCCESS";
const FB_SIGNUP_FAIL = "FB_SIGNUP_FAIL";

const SIGNUP_START = "SIGNUP_START";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAIL = "SIGNUP_FAIL";

const LOGIN_USER_START = "LOGIN_USER_START";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

const LOGOUT_USER_START = "LOGOUT_USER_START";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

const SIGNUP_USER_START = "SIGNUP_USER_START";
const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
const SIGNUP_USER_FAIL = " SIGNUP_USER_FAIL";

const FORGOT_PASS_START = "FORGOT_PASS_START";
const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
const FORGOT_PASS_FAIL = "FORGOT_PASS_FAIL";

const SAVE_CHAT_START = "SAVE_CHAT_START";
const SAVE_CHAT_SUCCESS = "SAVE_CHAT_SUCCESS";
const SAVE_CHAT_FAIL = "SAVE_CHAT_FAIL";

const SWITCH_MODE_SUCCESS = "SWITCH_MODE_SUCCESS";
const SWITCH_MODE_START = "SWITCH_MODE_START";

const RECENT_VIEW_CAR_LIST_START = "RECENT_VIEW_CAR_LIST_START";
const RECENT_VIEW_CAR_LIST_SUCCESS = "RECENT_VIEW_CAR_LIST_SUCCESS";
const RECENT_VIEW_CAR_LIST_FAIL = "RECENT_VIEW_CAR_LIST_FAIL";

const CAR_LIST_START = "CAR_LIST_START";
const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
const CAR_LIST_FAIL = "CAR_LIST_FAIL";

const CARLUX_LIST_START = "CARLUX_LIST_START";
const CARLUX_LIST_SUCCESS = "CARLUX_LIST_SUCCESS";
const CARLUX_LIST_FAIL = "CARLUX_LIST_FAIL";

const OWNER_CAR_LIST_START = "OWNER_CAR_LIST_START";
const OWNER_CAR_LIST_SUCCESS = "OWNER_CAR_LIST_SUCCESS";
const OWNER_CAR_LIST_FAIL = "OWNER_CAR_LIST_FAIL";

const OWNER_CARLUX_LIST_START = "OWNER_CARLUX_LIST_START";
const OWNER_CARLUX_LIST_SUCCESS = "OWNER_CARLUX_LIST_SUCCESS";
const OWNER_CARLUX_LIST_FAIL = "OWNER_CARLUX_LIST_FAIL";

const PARISH_LIST_START = "PARISH_LIST_START";
const PARISH_LIST_SUCCESS = "PARISH_LIST_SUCCESS";
const PARISH_LIST_FAIL = "PARISH_LIST_FAIL";

const CAR_TYPE_LIST_START = "CAR_TYPE_LIST_START";
const CAR_TYPE_LIST_SUCCESS = "CAR_TYPE_LIST_SUCCESS";
const CAR_TYPE_LIST_FAIL = "CAR_TYPE_LIST_FAIL";

const REVIEW_LIST_START = "REVIEW_LIST_START";
const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

const OWNER_REVIEW_LIST_START = "OWNER_REVIEW_LIST_START";
const OWNER_REVIEW_LIST_SUCCESS = "OWNER_REVIEW_LIST_SUCCESS";
const OWNER_REVIEW_LIST_FAIL = "OWNER_REVIEW_LIST_FAIL";

const COUNTRY_LIST_START = "COUNTRY_LIST_START";
const COUNTRY_LIST_SUCCESS = "COUNTRY_LIST_SUCCESS";
const COUNTRY_LIST_FAIL = "COUNTRY_LIST_FAIL";

const LANGUAGE_LIST_START = "LANGUAGE_LIST_START";
const LANGUAGE_LIST_SUCCESS = "LANGUAGE_LIST_SUCCESS";
const LANGUAGE_LIST_FAIL = "LANGUAGE_LIST_FAIL";

const PROFILE_DETAILS_START = "PROFILE_DETAILS_START";
const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";

const UPDATE_PHONE_NUMBER_START = "UPDATE_PHONE_NUMBER_START";
const UPDATE_PHONE_NUMBER_SUCCESS = "UPDATE_PHONE_NUMBER_SUCCESS";
const UPDATE_PHONE_NUMBER_FAIL = "UPDATE_PHONE_NUMBER_FAIL";

const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

const CLOSE_ACCOUNT_START = "CLOSE_ACCOUNT_START";
const CLOSE_ACCOUNT_SUCCESS = "CLOSE_ACCOUNT_SUCCESS";
const CLOSE_ACCOUNT_FAIL = "CLOSE_ACCOUNT_FAIL";

const DRIVER_LICENSE_CREATE_START = "DRIVER_LICENSE_CREATE_START";
const DRIVER_LICENSE_CREATE_SUCCESS = "DRIVER_LICENSE_CREATE_SUCCESS";
const DRIVER_LICENSE_CREATE_FAIL = "DRIVER_LICENSE_CREATE_FAIL";

const FAVOURITE_CAR_LIST_START = "FAVOURITE_CAR_LIST_START";
const FAVOURITE_CAR_LIST_SUCCESS = "FAVOURITE_CAR_LIST_SUCCESS";
const FAVOURITE_CAR_LIST_FAIL = "FAVOURITE_CAR_LIST_FAIL";

const FAVOURITE_CAR_ADD_START = "FAVOURITE_CAR_ADD_START";
const FAVOURITE_CAR_ADD_SUCCESS = "FAVOURITE_CAR_ADD_SUCCESS";
const FAVOURITE_CAR_ADD_FAIL = "FAVOURITE_CAR_ADD_FAIL";

const FAVOURITE_CAR_REMOVE_START = "FAVOURITE_CAR_REMOVE_START";
const FAVOURITE_CAR_REMOVE_SUCCESS = "FAVOURITE_CAR_REMOVE_SUCCESS";
const FAVOURITE_CAR_REMOVE_FAIL = "FAVOURITE_CAR_REMOVE_FAIL";

const CHAT_LIST_START = "CHAT_LIST_START";
const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";

const CALL_LIST_START = "CALL_LIST_START";
const CALL_LIST_SUCCESS = "CALL_LIST_SUCCESS";
const CALL_LIST_FAIL = "CALL_LIST_FAIL";

const CUSTOMER_CONTACT_LIST_START = "CUSTOMER_CONTACT_LIST_START";
const CUSTOMER_CONTACT_LIST_SUCCESS = "CUSTOMER_CONTACT_LIST_SUCCESS";
const CUSTOMER_CONTACT_LIST_FAIL = "CUSTOMER_CONTACT_LIST_FAIL";

const CHAT_MESSAGE_SEND_START = "CHAT_MESSAGE_SEND_START";
const CHAT_MESSAGE_SEND_SUCCESS = "CHAT_MESSAGE_SEND_SUCCESS";
const CHAT_MESSAGE_SEND_FAIL = "CHAT_MESSAGE_SEND_FAIL";

const CHAT_MESSAGE_HISTORY_START = "CHAT_MESSAGE_HISTORY_START";
const CHAT_MESSAGE_HISTORY_SUCCESS = "CHAT_MESSAGE_HISTORY_SUCCESS";
const CHAT_MESSAGE_HISTORY_FAIL = "CHAT_MESSAGE_HISTORY_FAIL";

const OWNER_CAR_VIEW_START = "OWNER_CAR_VIEW_START";
const OWNER_CAR_VIEW_SUCCESS = "OWNER_CAR_VIEW_SUCCESS";
const OWNER_CAR_VIEW_FAIL = "OWNER_CAR_VIEW_FAIL";

const CAR_VIEW_START = " CAR_VIEW_START";
const CAR_VIEW_SUCCESS = " CAR_VIEW_SUCCESS";
const CAR_VIEW_FAIL = "CAR_VIEW_FAIL";

const RESET_ALL = "RESET_ALL";

const CREATE_RENTAL_CAR_START = "CREATE_RENTAL_CAR_START";
const CREATE_RENTAL_CAR_SUCCESS = "CREATE_RENTAL_CAR_SUCCESS";
const CREATE_RENTAL_CAR_FAIL = "CREATE_RENTAL_CAR_FAIL";

const BOOKED_TRIP_LIST_START = "BOOKED_TRIP_LIST_START";
const BOOKED_TRIP_CAR_LIST_SUCCESS = "BOOKED_TRIP_CAR_LIST_SUCCESS";
const BOOKED_TRIP_CAR_LIST_FAIL = "BOOKED_TRIP_CAR_LIST_FAIL";

const MAKE_PAYMENT_START = "MAKE_PAYMENT_START";
const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";

const CANCEL_TRIP_START = "CANCEL_TRIP_START";
const CANCEL_TRIP_SUCCESS = "CANCEL_TRIP_SUCCESS";
const CANCEL_TRIP_FAIL = "CANCEL_TRIP_FAIL";

const HISTORY_TRIP_LIST_START = "HISTORY_TRIP_LIST_START";
const HISTORY_TRIP_LIST_SUCCESS = "HISTORY_TRIP_LIST_SUCCESS";
const HISTORY_TRIP_LIST_FAIL = "HISTORY_TRIP_LIST_FAIL";

const CHANGE_EMAIL_START = "CHANGE_EMAIL_START";
const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
const CHANGE_EMAIL_FAIL = "CHANGE_EMAIL_FAIL";

const SWITCH_TO_OWNER_START = "SWITCH_TO_OWNER_START";
const SWITCH_TO_OWNER_SUCCESS = "SWITCH_TO_OWNER_SUCCESS";
const SWITCH_TO_OWNER_FAIL = "SWITCH_TO_OWNER_FAIL";

const SWITCH_TO_CUSTOMER_START = "SWITCH_TO_CUSTOMER_START";
const SWITCH_TO_CUSTOMER_SUCCESS = "SWITCH_TO_CUSTOMER_SUCCESS";
const SWITCH_TO_CUSTOMER_FAIL = "SWITCH_TO_CUSTOMER_FAIL";

const CAR_BRAND_LIST_START = "CAR_BRAND_LIST_START";
const CAR_BRAND_LIST_SUCCESS = "CAR_BRAND_LIST_SUCCESS";
const CAR_BRAND_LIST_FAIL = "CAR_BRAND_LIST_FAIL";

const CAR_OWNER_CREATE_CAR_START = "CAR_OWNER_CREATE_CAR_START";
const CAR_OWNER_CREATE_CAR_SUCCESS = "CAR_OWNER_CREATE_CAR_SUCCESS";
const CAR_OWNER_CREATE_CAR_FAIL = "CAR_OWNER_CREATE_CAR_FAIL";

const RENTALCAR_VIEW_START = "RENTALCAR_VIEW_START";
const RENTALCAR_VIEW_SUCCESS = "RENTALCAR_VIEW_SUCCESS";
const RENTALCAR_VIEW_CAR_FAIL = "RENTALCAR_VIEW_FAIL";

const RENTALCAR_ADDRESS_START = "RENTALCAR_ADDRESS_START";
const RENTALCAR_ADDRESS_SUCCESS = "RENTALCAR_ADDRESS_SUCCESS";
const RENTALCAR_ADDRESS_FAIL = "RENTALCAR_ADDRESS_FAIL";

const RENTALCAR_DATES_START = "RENTALCAR_DATES_START";
const RENTALCAR_DATES_SUCCESS = "RENTALCAR_DATES_SUCCESS";
const RENTALCAR_DATES_FAIL = "RENTALCAR_DATES_FAIL";

const NAVIGATE_TAB_SCREEN = "NAVIGATE_TAB_SCREEN";

const FEATURE_LIST_START = "FEATURE_LIST_START";
const FEATURE_LIST_SUCCESS = "FEATURE_LIST_SUCCESS";
const FEATURE_LIST_FAIL = "FEATURE_LIST_FAIL";

const CAR_INFO_LIST_START = "CAR_INFO_LIST_START";
const CAR_INFO_LIST_SUCCESS = "CAR_INFO_LIST_SUCCESS";
const CAR_INFO_LIST_FAIL = "CAR_INFO_LIST_FAIL";

const CREATE_STRIPE_ACCOUNT_START = "CREATE_STRIPE_ACCOUNT_START";
const CREATE_STRIPE_ACCOUNT_SUCCESS = "CREATE_STRIPE_ACCOUNT_SUCCESS";
const CREATE_STRIPE_ACCOUNT_FAIL = "CREATE_STRIPE_ACCOUNT_FAIL";

const CARD_ACCESS_TOKEN_START = "CARD_ACCESS_TOKEN_START";
const CARD_ACCESS_TOKEN_SUCCESS = "CARD_ACCESS_TOKEN_SUCCESS";
const CARD_ACCESS_TOKEN_FAIL = "CARD_ACCESS_TOKEN_FAIL";

const SAVE_CARD_START = "SAVE_CARD_START";
const SAVE_CARD_SUCCESS = "SAVE_CARD_SUCCESS";
const SAVE_CARD_FAIL = "SAVE_CARD_FAIL";

const SAVE_CARDLIST_START = "SAVE_CARDLIST_START";
const SAVE_CARDLIST_SUCCESS = "SAVE_CARDLIST_SUCCESS";
const SAVE_CARDLIST_FAIL = "SAVE_CARDLIST_FAIL";

const UPLOAD_CAR_IMAGES_START = "UPLOAD_CAR_IMAGES_START";
const UPLOAD_CAR_IMAGES_SUCCESS = "UPLOAD_CAR_IMAGES_SUCCESS";
const UPLOAD_CAR_IMAGES_FAIL = "UPLOAD_CAR_IMAGES_FAIL";

const VIEW_CARD_START = "VIEW_CARD_START";
const VIEW_CARD_SUCCESS = "VIEW_CARD_SUCCESS";
const VIEW_CARD_FAIL = "VIEW_CARD_FAIL";

const UPDATE_CARD_START = "UPDATE_CARD_START";
const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
const UPDATE_CARD_FAIL = "UPDATE_CARD_FAIL";

const DELETE_CARD_START = "DELETE_CARD_START";
const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
const DELETE_CARD_FAIL = "DELETE_CARD_FAIL";
const INSURANCEPROTECTION_START = "INSURANCEPROTECTION_START";
const INSURANCEPROTECTION_SUCCESS = "INSURANCEPROTECTION_SUCCESS";
const INSURANCEPROTECTION_FAIL = "INSURANCEPROTECTION_FAIL";

const OWNER_TRANSACTION_LIST_START = "OWNER_TRANSACTION_LIST_START";
const OWNER_TRANSACTION_LIST_SUCCESS = "OWNER_TRANSACTION_LIST_SUCCESS";
const OWNER_TRANSACTION_LIST_FAIL = "OWNER_TRANSACTION_LIST_FAIL";

const CUSTOMER_CALL_START = "CUSTOMER_CALL_START";
const CUSTOMER_CALL_SUCCESS = "CUSTOMER_CALL_SUCCESS";
const CUSTOMER_CALL_FAIL = "CUSTOMER_CALL_FAIL";

const CUSTOMER_CALLEND_START = "CUSTOMER_CALLEND_START";
const CUSTOMER_CALLEND_SUCCESS = "CUSTOMER_CALLEND_SUCCESS";
const CUSTOMER_CALLEND_FAIL = "CUSTOMER_CALLEND_FAIL";

const CHANGE_MANUAL_TRANSMISSION_START = "CHANGE_MANUAL_TRANSMISSION_START";
const CHANGE_MANUAL_TRANSMISSION_SUCCESS = "CHANGE_MANUAL_TRANSMISSION_SUCCESS";
const CHANGE_MANUAL_TRANSMISSION_FAIL = "CHANGE_MANUAL_TRANSMISSION_FAIL";

const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

const BOOKING_CANCEL_START = "BOOKING_CANCEL_START";
const BOOKING_CANCEL_SUCCESS = "BOOKING_CANCEL_SUCCESS";
const BOOKING_CANCEL_FAIL = "BOOKING_CANCEL_FAIL";

const BOOKING_CANCEL_REASON_START = "BOOKING_CANCEL_REASON_START";
const BOOKING_CANCEL_REASON_SUCCESS = "BOOKING_CANCEL_REASON_SUCCESS";
const BOOKING_CANCEL_REASON_FAIL = "BOOKING_CANCEL_REASON_FAIL";
const VERIFY_OTP_START = "VERIFY_OTP_START";
const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

const RESEND_OTP_START = "RESEND_OTP_START";
const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
const RESEND_OTP_FAIL = "RESEND_OTP_FAIL";

const RESET_PASS_START = "RESET_PASS_START";
const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
const RESET_PASS_FAIL = "RESET_PASS_FAIL";

const VALIDATION_CHECK_START = "VALIDATION_CHECK_START";
const VALIDATION_CHECK_SUCCESS = "VALIDATION_CHECK_SUCCESS";
const VALIDATION_CHECK_FAIL = "VALIDATION_CHECK_FAIL";

const RESERVE_CAR_START = "RESERVE_CAR_START";
const RESERVE_CAR_SUCCESS = "RESERVE_CAR_SUCCESS";
const RESERVE_CAR_FAIL = "RESERVE_CAR_FAIL";

const EARNING_LIST_START = "EARNING_LIST_START";
const EARNING_LIST_SUCCESS = "EARNING_LIST_SUCCESS";
const EARNING_LIST_FAIL = "EARNING_LIST_FAIL";

const AMOUNT_DETAILS_START = "AMOUNT_DETAILS_START";
const AMOUNT_DETAILS_SUCCESS = "AMOUNT_DETAILS_SUCCESS";
const AMOUNT_DETAILS_FAIL = "AMOUNT_DETAILS_FAIL";

const STRIPE_PAYMENT_START = "STRIPE_PAYMENT_START";
const STRIPE_PAYMENT_SUCCESS = "STRIPE_PAYMENT_SUCCESS";
const STRIPE_PAYMENT_FAIL = "STRIPE_PAYMENT_FAIL";

const NOTIFICATION_SETTINGS_START = "NOTIFICATION_SETTINGS_START";
const NOTIFICATION_SETTINGS_SUCCESS = "NOTIFICATION_SETTINGS_SUCCESS";
const NOTIFICATION_SETTINGS_FAIL = "NOTIFICATION_SETTINGS_FAIL";

const ADD_UNAVAILABLEDATES_START = "ADD_UNAVAILABLEDATES_START";
const ADD_UNAVAILABLEDATES_SUCCESS = "ADD_UNAVAILABLEDATES_SUCCESS";
const ADD_UNAVAILABLEDATES_FAIL = "ADD_UNAVAILABLEDATES_FAIL";

const GET_UNAVAILABLEDATES_START = "GET_UNAVAILABLEDATES_START";
const GET_UNAVAILABLEDATES_SUCCESS = "GET_UNAVAILABLEDATES_SUCCESS";
const GET_UNAVAILABLEDATES_FAIL = "GET_UNAVAILABLEDATES_FAIL";

const CARD_UPDATE_START = "CARD_UPDATE_START";
const CARD_UPDATE_SUCCESS = "CARD_UPDATE_SUCCESS";
const CARD_UPDATE_FAIL = "CARD_UPDATE_FAIL";

const PROMO_LIST_START = "PROMO_LIST_START";
const PROMO_LIST_SUCCESS = "PROMO_LIST_SUCCESS";
const PROMO_LIST_FAIL = "PROMO_LIST_FAIL";

const STRIPE_BALANCE_START = "STRIPE_BALANCE_START";
const STRIPE_BALANCE_SUCCESS = "STRIPE_BALANCE_SUCCESS";
const STRIPE_BALANCE_FAIL = "STRIPE_BALANCE_FAIL";

const MAP_START = "MAP_START";
const MAP_SUCCESS = "MAP_SUCCESS";
const MAP_FAIL = "MAP_FAIL";

const STRIPE_ACC_DETAILS_START = "STRIPE_ACC_DETAILS_START";
const STRIPE_ACC_DETAILS_SUCCESS = "STRIPE_ACC_DETAILS_SUCCESS";
const STRIPE_ACC_DETAILS_FAIL = "STRIPE_ACC_DETAILS_FAIL";

const ADD_FUND_START = "ADD_FUND_START";
const ADD_FUND_SUCCESS = "ADD_FUND_SUCCESS";
const ADD_FUND_FAIL = "ADD_FUND_FAIL";

const CAR_OWNER_UPDATE_CAR_START = "CAR_OWNER_UPDATE_CAR_START";
const CAR_OWNER_UPDATE_CAR_SUCCESS = "CAR_OWNER_UPDATE_CAR_SUCCESS";
const CAR_OWNER_UPDATE_CAR_FAIL = "CAR_OWNER_UPDATE_CAR_FAIL";

const CREATE_BANKACC_START = "CREATE_BANKACC_START";
const CREATE_BANKACC_SUCCESS = "CREATE_BANKACC_SUCCESS";
const CREATE_BANKACC_FAIL = "CREATE_BANKACC_FAIL";

const OWNER_TH_LIST_START = "OWNER_TH_LIST_START";
const OWNER_TH_LIST_SUCCESS = "OWNER_TH_LIST_SUCCESS";
const OWNER_TH_LIST_FAIL = "OWNER_TH_LIST_FAIL";

const BLOCK_CUSTOMER_START = "BLOCK_CUSTOMER_START";
const BLOCK_CUSTOMER_SUCCESS = "BLOCK_CUSTOMER_SUCCESS";
const BLOCK_CUSTOMER_FAIL = "BLOCK_CUSTOMER_FAIL";

const COMPLETE_BOOKING_START = "COMPLETE_BOOKING_START";
const COMPLETE_BOOKING_SUCCESS = "COMPLETE_BOOKING_SUCCESS";
const COMPLETE_BOOKING_FAIL = "COMPLETE_BOOKING_FAIL";

const REVIEW_START = "REVIEW_START";
const REVIEW_SUCCESS = "REVIEW_SUCCESS";
const REVIEW_FAIL = "REVIEW_FAIL";

const RESERVECAR_BOOK_START = "RESERVECAR_BOOK_START";
const RESERVECAR_BOOK_SUCCESS = "RESERVECAR_BOOK_SUCCESS";
const RESERVECAR_BOOK_FAIL = "RESERVECAR_BOOK_FAIL";

const UPDATE_BANK_DETAILS_START = "UPDATE_BANK_DETAILS_START";
const UPDATE_BANK_DETAILS_SUCCESS = "UPDATE_BANK_DETAILS_SUCCESS";
const UPDATE_BANK_DETAILS_FAIL = "UPDATE_BANK_DETAILS_FAIL";

const REFUND_AMOUNT_START = "REFUND_AMOUNT_START";
const REFUND_AMOUNT_SUCCESS = "REFUND_AMOUNT_SUCCESS";
const REFUND_AMOUNT_FAIL = "REFUND_AMOUNT_FAIL";

const REFRESH_TOKEN_START = "REFRESH_TOKEN_START";
const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

const RENTALCAR_PI_START = "RENTALCAR_PI_START";
const RENTALCAR_PI_SUCCESS = "RENTALCAR_PI_SUCCESS";
const RENTALCAR_PI_FAIL = "RENTALCAR_PI_FAIL";

const CONFIRM_PAYMENT_START = "CONFIRM_PAYMENT_START";
const CONFIRM_PAYMENT_SUCCESS = "CONFIRM_PAYMENT_SUCCESS";
const CONFIRM_PAYMENT_FAIL = "CONFIRM_PAYMENT_FAIL";

export const Action = {
  RESET_ALL,
  GOOGLE_SIGNUP_START,
  GOOGLE_SIGNUP_SUCCESS,
  GOOGLE_SIGNUP_FAIL,
  FB_SIGNUP_START,
  FB_SIGNUP_SUCCESS,
  FB_SIGNUP_FAIL,
  SIGNUP_START,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  LOGIN_USER_START,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAIL,
  LOGOUT_USER_START,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_FAIL,
  SIGNUP_USER_START,
  SIGNUP_USER_SUCCESS,
  SIGNUP_USER_FAIL,
  FORGOT_PASS_START,
  FORGOT_PASS_SUCCESS,
  FORGOT_PASS_FAIL,
  SAVE_CHAT_START,
  SAVE_CHAT_SUCCESS,
  SAVE_CHAT_FAIL,
  SWITCH_MODE_SUCCESS,
  SWITCH_MODE_START,

  CAR_TYPE_LIST_START,
  CAR_TYPE_LIST_SUCCESS,
  CAR_TYPE_LIST_FAIL,

  CAR_LIST_START,
  CAR_LIST_SUCCESS,
  CAR_LIST_FAIL,

  OWNER_CARLUX_LIST_START,
  OWNER_CARLUX_LIST_SUCCESS,
  OWNER_CARLUX_LIST_FAIL,

  OWNER_CAR_LIST_START,
  OWNER_CAR_LIST_SUCCESS,
  OWNER_CAR_LIST_FAIL,

  RECENT_VIEW_CAR_LIST_START,
  RECENT_VIEW_CAR_LIST_SUCCESS,
  RECENT_VIEW_CAR_LIST_FAIL,

  PARISH_LIST_START,
  PARISH_LIST_SUCCESS,
  PARISH_LIST_FAIL,

  REVIEW_LIST_START,
  REVIEW_LIST_SUCCESS,
  REVIEW_LIST_FAIL,

  OWNER_REVIEW_LIST_START,
  OWNER_REVIEW_LIST_SUCCESS,
  OWNER_REVIEW_LIST_FAIL,

  LANGUAGE_LIST_START,
  LANGUAGE_LIST_SUCCESS,
  LANGUAGE_LIST_FAIL,

  COUNTRY_LIST_START,
  COUNTRY_LIST_SUCCESS,
  COUNTRY_LIST_FAIL,

  PROFILE_DETAILS_START,
  PROFILE_DETAILS_SUCCESS,
  PROFILE_DETAILS_FAIL,

  UPDATE_PHONE_NUMBER_START,
  UPDATE_PHONE_NUMBER_SUCCESS,
  UPDATE_PHONE_NUMBER_FAIL,

  UPDATE_PROFILE_START,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAIL,

  CLOSE_ACCOUNT_START,
  CLOSE_ACCOUNT_SUCCESS,
  CLOSE_ACCOUNT_FAIL,

  DRIVER_LICENSE_CREATE_START,
  DRIVER_LICENSE_CREATE_SUCCESS,
  DRIVER_LICENSE_CREATE_FAIL,

  FAVOURITE_CAR_LIST_START,
  FAVOURITE_CAR_LIST_SUCCESS,
  FAVOURITE_CAR_LIST_FAIL,

  FAVOURITE_CAR_ADD_START,
  FAVOURITE_CAR_ADD_SUCCESS,
  FAVOURITE_CAR_ADD_FAIL,

  FAVOURITE_CAR_REMOVE_START,
  FAVOURITE_CAR_REMOVE_SUCCESS,
  FAVOURITE_CAR_REMOVE_FAIL,

  CHAT_LIST_START,
  CHAT_LIST_SUCCESS,
  CHAT_LIST_FAIL,

  CALL_LIST_START,
  CALL_LIST_SUCCESS,
  CALL_LIST_FAIL,

  CUSTOMER_CONTACT_LIST_START,
  CUSTOMER_CONTACT_LIST_SUCCESS,
  CUSTOMER_CONTACT_LIST_FAIL,

  CHAT_MESSAGE_SEND_START,
  CHAT_MESSAGE_SEND_SUCCESS,
  CHAT_MESSAGE_SEND_FAIL,

  CHAT_MESSAGE_HISTORY_START,
  CHAT_MESSAGE_HISTORY_SUCCESS,
  CHAT_MESSAGE_HISTORY_FAIL,

  CAR_VIEW_START,
  CAR_VIEW_SUCCESS,
  CAR_VIEW_FAIL,

  OWNER_CAR_VIEW_START,
  OWNER_CAR_VIEW_SUCCESS,
  OWNER_CAR_VIEW_FAIL,

  CREATE_RENTAL_CAR_FAIL,
  CREATE_RENTAL_CAR_START,
  CREATE_RENTAL_CAR_SUCCESS,

  BOOKED_TRIP_LIST_START,
  BOOKED_TRIP_CAR_LIST_SUCCESS,
  BOOKED_TRIP_CAR_LIST_FAIL,

  HISTORY_TRIP_LIST_START,
  HISTORY_TRIP_LIST_SUCCESS,
  HISTORY_TRIP_LIST_FAIL,

  CHANGE_EMAIL_START,
  CHANGE_EMAIL_SUCCESS,
  CHANGE_EMAIL_FAIL,

  SWITCH_TO_OWNER_START,
  SWITCH_TO_OWNER_SUCCESS,
  SWITCH_TO_OWNER_FAIL,

  SWITCH_TO_CUSTOMER_START,
  SWITCH_TO_CUSTOMER_SUCCESS,
  SWITCH_TO_CUSTOMER_FAIL,

  CAR_BRAND_LIST_START,
  CAR_BRAND_LIST_SUCCESS,
  CAR_BRAND_LIST_FAIL,

  CAR_OWNER_CREATE_CAR_START,
  CAR_OWNER_CREATE_CAR_SUCCESS,
  CAR_OWNER_CREATE_CAR_FAIL,

  NAVIGATE_TAB_SCREEN,

  RENTALCAR_VIEW_START,
  RENTALCAR_VIEW_SUCCESS,
  RENTALCAR_VIEW_CAR_FAIL,

  RENTALCAR_DATES_START,
  RENTALCAR_DATES_SUCCESS,
  RENTALCAR_DATES_FAIL,

  RENTALCAR_ADDRESS_START,
  RENTALCAR_ADDRESS_SUCCESS,
  RENTALCAR_ADDRESS_FAIL,

  FEATURE_LIST_START,
  FEATURE_LIST_SUCCESS,
  FEATURE_LIST_FAIL,

  CAR_INFO_LIST_START,
  CAR_INFO_LIST_SUCCESS,
  CAR_INFO_LIST_FAIL,

  CREATE_STRIPE_ACCOUNT_FAIL,
  CREATE_STRIPE_ACCOUNT_START,
  CREATE_STRIPE_ACCOUNT_SUCCESS,

  CARD_ACCESS_TOKEN_FAIL,
  CARD_ACCESS_TOKEN_START,
  CARD_ACCESS_TOKEN_SUCCESS,

  SAVE_CARD_START,
  SAVE_CARD_SUCCESS,
  SAVE_CARD_FAIL,

  SAVE_CARDLIST_START,
  SAVE_CARDLIST_SUCCESS,
  SAVE_CARDLIST_FAIL,

  UPLOAD_CAR_IMAGES_START,
  UPLOAD_CAR_IMAGES_SUCCESS,
  UPLOAD_CAR_IMAGES_FAIL,

  VIEW_CARD_FAIL,
  VIEW_CARD_START,
  VIEW_CARD_SUCCESS,

  UPDATE_CARD_FAIL,
  UPDATE_CARD_START,
  UPDATE_CARD_SUCCESS,

  DELETE_CARD_FAIL,
  DELETE_CARD_START,
  DELETE_CARD_SUCCESS,

  CANCEL_TRIP_START,
  CANCEL_TRIP_SUCCESS,
  CANCEL_TRIP_FAIL,

  MAKE_PAYMENT_FAIL,
  MAKE_PAYMENT_START,
  MAKE_PAYMENT_SUCCESS,

  INSURANCEPROTECTION_START,
  INSURANCEPROTECTION_SUCCESS,
  INSURANCEPROTECTION_FAIL,

  OWNER_TRANSACTION_LIST_START,
  OWNER_TRANSACTION_LIST_SUCCESS,
  OWNER_TRANSACTION_LIST_FAIL,

  CUSTOMER_CALL_START,
  CUSTOMER_CALL_SUCCESS,
  CUSTOMER_CALL_FAIL,

  CUSTOMER_CALLEND_START,
  CUSTOMER_CALLEND_SUCCESS,
  CUSTOMER_CALLEND_FAIL,

  CHANGE_MANUAL_TRANSMISSION_START,
  CHANGE_MANUAL_TRANSMISSION_SUCCESS,
  CHANGE_MANUAL_TRANSMISSION_FAIL,

  CHANGE_PASSWORD_START,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAIL,

  BOOKING_CANCEL_START,
  BOOKING_CANCEL_SUCCESS,
  BOOKING_CANCEL_FAIL,

  BOOKING_CANCEL_REASON_START,
  BOOKING_CANCEL_REASON_SUCCESS,
  BOOKING_CANCEL_REASON_FAIL,

  VALIDATION_CHECK_START,
  VALIDATION_CHECK_SUCCESS,
  VALIDATION_CHECK_FAIL,

  VERIFY_OTP_START,
  VERIFY_OTP_SUCCESS,
  VERIFY_OTP_FAIL,

  RESEND_OTP_START,
  RESEND_OTP_SUCCESS,
  RESEND_OTP_FAIL,

  RESET_PASS_START,
  RESET_PASS_SUCCESS,
  RESET_PASS_FAIL,

  RESERVE_CAR_FAIL,
  RESERVE_CAR_START,
  RESERVE_CAR_SUCCESS,

  EARNING_LIST_START,
  EARNING_LIST_SUCCESS,
  EARNING_LIST_FAIL,
  AMOUNT_DETAILS_FAIL,
  AMOUNT_DETAILS_START,
  AMOUNT_DETAILS_SUCCESS,

  STRIPE_PAYMENT_FAIL,
  STRIPE_PAYMENT_START,
  STRIPE_PAYMENT_SUCCESS,

  NOTIFICATION_SETTINGS_START,
  NOTIFICATION_SETTINGS_SUCCESS,
  NOTIFICATION_SETTINGS_FAIL,

  ADD_UNAVAILABLEDATES_START,
  ADD_UNAVAILABLEDATES_SUCCESS,
  ADD_UNAVAILABLEDATES_FAIL,

  GET_UNAVAILABLEDATES_START,
  GET_UNAVAILABLEDATES_SUCCESS,
  GET_UNAVAILABLEDATES_FAIL,

  CARD_UPDATE_START,
  CARD_UPDATE_SUCCESS,
  CARD_UPDATE_FAIL,

  PROMO_LIST_START,
  PROMO_LIST_SUCCESS,
  PROMO_LIST_FAIL,

  STRIPE_BALANCE_START,
  STRIPE_BALANCE_SUCCESS,
  STRIPE_BALANCE_FAIL,

  MAP_FAIL,
  MAP_START,
  MAP_SUCCESS,

  CARLUX_LIST_FAIL,
  CARLUX_LIST_START,
  CARLUX_LIST_SUCCESS,

  STRIPE_ACC_DETAILS_START,
  STRIPE_ACC_DETAILS_SUCCESS,
  STRIPE_ACC_DETAILS_FAIL,

  ADD_FUND_START,
  ADD_FUND_SUCCESS,
  ADD_FUND_FAIL,

  CAR_OWNER_UPDATE_CAR_START,
  CAR_OWNER_UPDATE_CAR_SUCCESS,
  CAR_OWNER_UPDATE_CAR_FAIL,

  CREATE_BANKACC_FAIL,
  CREATE_BANKACC_START,
  CREATE_BANKACC_SUCCESS,

  OWNER_TH_LIST_START,
  OWNER_TH_LIST_SUCCESS,
  OWNER_TH_LIST_FAIL,

  BLOCK_CUSTOMER_START,
  BLOCK_CUSTOMER_SUCCESS,
  BLOCK_CUSTOMER_FAIL,

  COMPLETE_BOOKING_START,
  COMPLETE_BOOKING_SUCCESS,
  COMPLETE_BOOKING_FAIL,

  REVIEW_FAIL,
  REVIEW_START,
  REVIEW_SUCCESS,

  RESERVECAR_BOOK_START,
  RESERVECAR_BOOK_SUCCESS,
  RESERVECAR_BOOK_FAIL,

  REFUND_AMOUNT_START,
  REFUND_AMOUNT_SUCCESS,
  REFUND_AMOUNT_FAIL,

  UPDATE_BANK_DETAILS_START,
  UPDATE_BANK_DETAILS_SUCCESS,
  UPDATE_BANK_DETAILS_FAIL,

  REFRESH_TOKEN_START,
  REFRESH_TOKEN_SUCCESS,
  REFRESH_TOKEN_FAIL,

  RENTALCAR_PI_START,
  RENTALCAR_PI_SUCCESS,
  RENTALCAR_PI_FAIL,

  CONFIRM_PAYMENT_START,
  CONFIRM_PAYMENT_SUCCESS,
  CONFIRM_PAYMENT_FAIL,
};
