export const countryData = [
  {label: 'India', value: 'India'},
  {label: 'United States', value: 'United States'},
  {label: 'United kingdom', value: 'United kingdom'},
  {label: 'Afghanistan', value: 'Afghanistan'},
  {label: 'Albania', value: 'Albania'},
  {label: 'Algeria', value: 'Algeria'},
  {label: 'Andorra', value: 'Andorra'},
  {label: 'Angola', value: 'Angola'},
  {label: 'Antigua', value: 'Antigua'},
  {label: 'Argentina', value: 'Argentina'},
  {label: 'Armenia', value: 'Armenia'},
  {label: 'Australia', value: 'Australia'},
  {label: 'Autria', value: 'Autria'},
  {label: 'Azerbaijan', value: 'Azerbaijan'},
  {label: 'Bahamas', value: 'Bahamas'},
  {label: 'Bahrain', value: 'Bahrain'},
  {label: 'Bangladesh', value: 'Bangladesh'},
  {label: 'Barbades', value: 'Barbades'},
  {label: 'Belarus', value: 'Belarus'},
  {label: 'Belize', value: 'Belize'},
];

export const provinceData = [
  {label: 'Clarendon', value: 'Clarendon', id: 1},
  {label: 'Hanover', value: 'Hanover', id: 2},
  {label: 'Kingston Parish', value: 'Kingston Parish', id: 3},
  {label: 'Manchester', value: 'Manchester', id: 4},
  {label: 'Portland', value: 'Portland', id: 5},
  {label: 'Saint Ann', value: 'Saint Ann', id: 6},
  {label: 'Saint Andrews', value: 'Saint Andrews', id: 7},
  {label: 'Saint Elizabeth', value: 'Saint Elizabeth', id: 8},
  {label: 'Saint Catherine', value: 'Saint Catherine', id: 9},
  {label: ' Saint James', value: ' Saint James', id: 10},
  {label: 'Saint Mary', value: 'Saint Mary', id: 11},
  {label: 'Trelany', value: 'Trelany', id: 12},
];
