export const WalletData = [
  {
    id: 1,
    name: "Daniel Austin",
    date: "Dec 20, 2024",
    time: "10:00 AM",
    userImg: require("../../assets/Images/UserImages/user1.jpg"),
    amount: "$14",
    type: "Taxi Expense",
  },
  {
    id: 2,
    name: "Top Up Wallet",
    date: "Dec 16, 2024",
    time: "16:42 PM",
    userImg: require("../../assets/Images/TransactionWallet.png"),
    amount: "$80",
    type: "Top Up",
  },
  {
    id: 3,
    name: "Sarah Wilson",
    date: "Dec 14, 2024",
    time: "11:39 AM",
    userImg: require("../../assets/Images/UserImages/user3.jpg"),
    amount: "$26",
    type: "Taxi Expense",
  },
  {
    id: 4,
    name: "Benny Spanbauer",
    date: "Dec 09, 2024",
    time: "14:46 PM",
    userImg: require("../../assets/Images/UserImages/user4.jpg"),
    amount: "$24",
    type: "Taxi Expense",
  },
  {
    id: 5,
    name: "Top Up Wallet",
    date: "Dec 02, 2024",
    time: "09:27 AM",
    userImg: require("../../assets/Images/TransactionWallet.png"),
    amount: "$100",
    type: "Top Up",
  },
  {
    id: 6,
    name: "Roselle Ehrman",
    date: "Nov 28, 2024",
    time: "13:56 PM",
    userImg: require("../../assets/Images/UserImages/user1.jpg"),
    amount: "$18",
    type: "Taxi Expense",
  },
  // {
  //   id: 7,
  //   name: "Florencio Dorrance",
  //   date: "Nov 23, 2024",
  //   time: "15:44 PM",
  //   userImg: require("../../assets/Images/UserImages/user2.jpg"),
  //   amount: "$15",
  //   type: "Taxi Expense",
  // },
  {
    id: 9,
    name: "Top Up Wallet",
    date: "Nov 14, 2024",
    time: "18:49 PM",
    userImg: require("../../assets/Images/TransactionWallet.png"),
    amount: "$150",
    type: "Top Up",
  },
];
